spring.application.name=profile

spring.datasource.url=jdbc:postgresql://localhost:5432/user-profile
spring.datasource.username=postgres
spring.datasource.password=L@p0$123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true